### ISSUE TITLE
Mismatch in UPS name docker environment variable and value in python script

### ISSUE THREAD

**Issue by grigsby** [mihai-cindea/nut-influxdb-exporter#10]
There is a mismatch between the docker environment variable and the line used to set the name of the UPS in the python script nut-influxdb-exporter.py.

The docker environment variable is NUT_ALIAS

The corresponding line 23 in the python code is:

ups_alias = os.getenv('UPS_ALIAS', 'UPS')

These need to match -- the docker environment variable UPS_ALIAS does not exist, so the container won't connect to a remote NUT server if the UPS has a different name than the default 'UPS.'

 It will produce an error:

Traceback (most recent call last):
File "/src/nut-influxdb-exporter.py", line 107, in <module>
json_body = construct_object(ups_data, remove_keys, tag_keys)
NameError: name 'ups_data' is not defined
Connecting to InfluxDB host:192.168.1.4, DB:telegraf
Connected successfully to InfluxDB
Connecting to NUT host 192.168.1.4:3493
Connected successfully to NUT
Error getting data from NUT

Recommended fix:

Change the docker environment variable to UPS_NAME
Change line 23 in nut-influxdb-exporter.py to:
ups_alias = os.getenv('UPS_NAME', 'UPS')

The current docker environment variable named NUT_ALIAS is confusing, as there's no indication what this refers to. Changing the variable to "UPS_NAME" in both places will match the wording in the unraid NUT settings panel.

**Comment by mcindea** [comment]
Good point, fixed it [here](https://github.com/kiwimato/nut-influxdb-exporter/commit/3a6fb84094fdaed9bfa2224f4d99cb1da43100fe)
Let me know what you think.

**Comment by grigsby** [comment]
Thank you! Looks great!
