### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by drbw** [mihai-cindea/nut-influxdb-exporter#6]
This project is unlicensed and as such cannot be actually used as Open Source by anyone. Please consider adding a license if the current copyright holders can agree on one.

**Comment by mcindea** [comment]
good point. It's my first project so didn't think much about it. I need to study which is the best for an open source project since I don't know much. Would GPL be a good match? or do you have any suggestions?

**Comment by drbw** [comment]
GitHub has created its own licensing overwiew here: https://choosealicense.com/licenses/

Personally, I prefer more permissive licenses, especially the MPL. But I'm not a lawyer so I can't advise on the finer points of this.

**Comment by mcindea** [comment]
Added MLP license, feel free let me know if there's anything else.
