### ISSUE TITLE
Nothing being written to database?

### ISSUE THREAD

**Issue by J89eu** [mihai-cindea/nut-influxdb-exporter#9]
Hi there, I'm getting an issue whereby I don't believe anything is being written to the database, not sure what is the issue but this is the debug info from the Unraid docker log

```
Connecting to InfluxDB host:192.168.1.5, DB:nut
Connected successfully to InfluxDB
INFLUXDB_DATABASE: nut
INFLUXDB_USER:
INFLUXDB_PORT: 8086
INFLUXDB_HOST: 192.168.1.5
NUT_USER: monuser
UPS_ALIAS UPS
INTERVAL: 21.0
VERBOSE: true
Connecting to NUT host 192.168.1.5:3493
[DEBUG] Class initialization...
[DEBUG] -> Host = 192.168.1.5 (port 3493)
[DEBUG] -> Login = 'user removed' / 'pw removed'
[DEBUG] Connecting to host
Connected successfully to NUT
[DEBUG] list_vars called...
Traceback (most recent call last):
File "/src/nut-influxdb-exporter.py", line 107, in <module>
json_body = construct_object(ups_data, remove_keys, tag_keys)
File "/src/nut-influxdb-exporter.py", line 85, in construct_object
fields['watts'] = watts * 0.01 * fields['ups.load']
KeyError: 'ups.load'
```

Any ideas what could be causing this?

**Comment by mcindea** [comment]
Sorry for the delay.
Interesting. It seems NUT doesn't provide ups.load.
You could use `nc` to try and see what output you get:
```
root@Rick:~# nc localhost 3493 -v
Rick [127.0.0.1] 3493 (nut) open
USERNAME <>
OK
PASSWORD <>
OK
LIST VAR UPS
<snip>
VAR UPS ups.load "22"
</snip>
```
If the load is reported some other way we need to adapt the script.

**Comment by mcindea** [comment]
btw, example of expected output: https://github.com/kiwimato/nut-influxdb-exporter/issues/3

**Comment by mcindea** [comment]
@J89eu would it be possible to get an output of what the NUT daemon sends? I find it really odd that `ups.load` is not sent.

**Comment by J89eu** [comment]
Hi, I think I ended up coming to the conclusion it was my UPS not sending the data rather than the exporter not saving it to InfluxDB. I never thought to check that with it being a fairly decent APC one!

**Comment by mcindea** [comment]
Interesting. If you own a APC you might not nee NUT really after all, have you tried this? https://github.com/atribe/apcupsd-influxdb-exporter

**Comment by mcindea** [comment]
Closing this issue, feel free to open another one in case you still have issues.
